import qrcode
from io import BytesIO
from fpdf import FPDF
from app.utils.security import generate_signature
from app.core.config import settings

def create_qr_code(task_id: str, signature: str) -> BytesIO:
    """Generates a QR code pointing to the verification URL."""
    verify_url = f"https://greencompute.io/verify/{task_id}?sig={signature}"
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(verify_url)
    qr.make(fit=True)
    
    img = qr.make_image(fill_color="black", back_color="white")
    img_byte_arr = BytesIO()
    img.save(img_byte_arr, format='PNG')
    img_byte_arr.seek(0)
    return img_byte_arr

class ESGReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Green-Compute: ESG Carbon Savings Certificate', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by Green-Compute Middleware - Page {self.page_no()}', 0, 0, 'C')

def generate_certificate(task_data: dict) -> bytes:
    """Generates a PDF certificate with task details and QR code."""
    pdf = ESGReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Task Info
    pdf.cell(200, 10, txt=f"Task ID: {task_data['request_id']}", ln=True)
    pdf.cell(200, 10, txt=f"Status: {task_data['status']}", ln=True)
    pdf.cell(200, 10, txt=f"Priority: {task_data['priority']}", ln=True)
    pdf.ln(5)
    
    # Carbon Metrics
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, txt=f"Carbon Performance:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"- Carbon Intensity at Execution: {task_data['intensity_at_execution']} gCO2/kWh", ln=True)
    pdf.cell(200, 10, txt=f"- CO2 Baseline (Immediate): {task_data['baseline_emissions']} g", ln=True)
    pdf.cell(200, 10, txt=f"- CO2 Actual (Optimized): {task_data['actual_emissions']} g", ln=True)
    pdf.set_text_color(0, 128, 0) # Green
    pdf.cell(200, 10, txt=f"- Net Carbon Saved: {task_data['carbon_saved']} g", ln=True)
    pdf.set_text_color(0, 0, 0) # Black
    
    # QR Code
    signature = generate_signature(task_data['request_id'])
    qr_img = create_qr_code(task_data['request_id'], signature)
    
    # Save QR temp
    with open("temp_qr.png", "wb") as f:
        f.write(qr_img.getbuffer())
        
    pdf.image("temp_qr.png", x=150, y=50, w=40)
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, "This certificate verifies that the AI task was computed during a window of high grid renewable energy penetration, significantly reducing its environment impact.")

    return pdf.output(dest='S')
